### ISSUE TITLE
Create multiple SCSS files

### ISSUE THREAD

**Issue by srjlulla** [bootscore/bootscore-child#16]
First of all, incredible theme + exceptional work & support. Kudos to you guys!

I have a doubt that I've been circling around for a while now. I use css/scss/_bscore_custom.scss for all the global custom SCSS.

However, I have a habit of creating separate CSS files for one-off pages to improve performance.

**Main question** - is there a way to create multiple custom SCSS files that are not combined together?

**Comment by crftwrk** [comment]
Closed by https://github.com/bootscore/bootscore/issues/137
