### ISSUE TITLE
style.css: incorrect Template value

### ISSUE THREAD

**Issue by neralex** [bootscore/bootscore-child#33]
The template-value is set to: "bootscore-main" and it has to be "bootscore". Otherwise the child-theme will not be aailable in on the theme-dashboard.

**Comment by crftwrk** [comment]
No, that is correct. All themes and plugins here have `-main` suffix in their folder name. Main-theme's folder is `bootscore-main` https://github.com/bootscore/bootscore/releases/download/v5.3.4/bootscore-main.zip.

**Comment by crftwrk** [comment]
Pinned this issue to the top because as far as I remember, we had the same question already in the past.
