### ISSUE TITLE
Child theme crashing site

### ISSUE THREAD

**Issue by Rhatur** [bootscore/bootscore-child#9]
Hello,

I just downloaded the main bootstcore theme and the child theme.
After I installed both on my fresh Wordpress installation, I can navigate the site with the parent theme activated.
But when I activated the child theme, I can't load the website anymore.
The progress bar on the browser starts loading but gets stuck right away and won't move.

Do I need to do something else than uploading and activating the theme?

Thank you.

**Comment by crftwrk** [comment]
Hello Rhatur,

installed a fresh WordPress, bootscore, bootscore-child and activated it. Works fine. BTW a link to your site will be very helpful to help.

Please check this:

- are you sure that you installed bootscore-child and **not** bootcommerce-child? bootcommerce-child needs WooCommerce to work.
- Activate a default WP theme like Twenty Twenty-One and delete booth bootscore themes.
- Download and install bootscore https://github.com/bootscore/bootscore.
- Download and install bootscore-child https://github.com/bootscore/bootscore-child.
- Activate it.

Does this help?

**Comment by Rhatur** [comment]
Thanks for your answer crftwrk,

I was downloading the files from my account and not directly from Github so I tried with your link.
After waiting over 20 minutes, I finally got this error on my site:

`
Call Stack
--
1 | 16807695932.5350 | 366256 | {main}( ) | .../index.php:0
2 | 16807695932.5350 | 366568 | require( '/Users/arthur/Sites/Local Sites/magic-bears-studio/app/public/wp-blog-header.php ) | .../index.php:17
3 | 16807695932.5350 | 2782664 | require_once( '/Users/arthur/Sites/Local Sites/magic-bears-studio/app/public/wp-includes/template-loader.php ) | .../wp-blog-header.php:19
4 | 16807695932.5350 | 2848776 | include( '/Users/arthur/Sites/Local Sites/magic-bears-studio/app/public/wp-content/themes/bootscore-main/index.php ) | .../template-loader.php:106
5 | 16807695932.5350 | 2848776 | get_header( ) | .../index.php:16
6 | 16807695932.5350 | 2849152 | locate_template( ) | .../general-template.php:48
7 | 16807695932.5350 | 2849312 | load_template( ) | .../template.php:716
8 | 16807695932.5350 | 2849952 | require_once( '/Users/arthur/Sites/Local Sites/magic-bears-studio/app/public/wp-content/themes/bootscore-main/header.php ) | .../template.php:770
9 | 16807695932.5350 | 2859360 | wp_head( ) | .../header.php:29
10 | 16807695932.5350 | 2859360 | do_action( ) | .../general-template.php:3015
11 | 16807695932.5350 | 2859736 | WP_Hook->do_action( ) | .../plugin.php:470
12 | 16807695932.5350 | 2859736 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:327
13 | 16807695932.5350 | 2862816 | wp_enqueue_scripts( ) | .../class-wp-hook.php:303
14 | 16807695932.5350 | 2862816 | do_action( ) | .../script-loader.php:2083
15 | 16807695932.5350 | 2863192 | WP_Hook->do_action( ) | .../plugin.php:470
16 | 16807695932.5350 | 2863192 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:327
17 | 16807695932.5350 | 2865176 | bootscore_child_enqueue_styles( ) | .../class-wp-hook.php:303
18 | 16807695932.5350 | 2865624 | filemtime ( ) | .../functions.php:11
`
<img width="2240" alt="Screenshot 2021-12-09 at 11 14 00" src="https://user-images.githubusercontent.com/9843880/145386641-bcbfb951-bf48-4359-91c8-99b1bf240cca.png">

I am using Local by flywheel and out of curiosity I decided to tried on a live server and there I didn't get any issue.
Any idea on how to use the theme on a local installation?

Thanks for your help!

**Comment by crftwrk** [comment]
Maybe theme doesn't like flywheel. I use mamp for local installations and works fine. 

Try one of this:
- https://www.apachefriends.org/
- https://www.mamp.info/
- https://localwp.com

**Comment by Rhatur** [comment]
I am using https://localwp.com.

**Comment by crftwrk** [comment]
You got this error by using localwp? Please try https://www.apachefriends.org or https://www.mamp.info/ instead.

**Comment by Rhatur** [comment]
Well I am sorry but I can't change the full process for local development.
I'll dig some more information about this issue in the next weeks and get back to you.

Thanks for your help.

**Comment by crftwrk** [comment]
Thanks
